[ -f "/sys/devices/virtual/dmi/id/product_family" ] && HOST="$(cat /sys/devices/virtual/dmi/id/product_family)" || HOST="$(awk '/Model/ {print $3,$4,$5,$6,$7,$8}' /proc/cpuinfo)"

OS="$(awk -F '"' '/PRETTY_NAME/ {print $2}' /etc/os-release)"
ARCH="$(uname -m)"
CHAR_N="$(echo -n "$USER@$HOSTNAME" | wc -c)"
BAR="$(for ((i = 1 ; i <= $CHAR_N ; i++)); do echo -n "-" ; done)"
KERNEL="$(uname -r)"
PACKAGES="$(xbps-query -l | wc -l) (xbps-query)"
BASH_V="$(bash --version | awk '/GNU bash/ {print $4}')"

echo " "
echo -e "           ___           \033[1m$USER\033[0m@\033[1m$HOSTNAME\033[0m"
echo "        ,'    .',        $BAR"
echo -e "       /       \ \       \033[1mOS:\033[0m $OS $ARCH"
echo -e "      (,.,.,.,.,.,)      \033[1mHost:\033[0m $HOST"
echo -e "   ,   ) ) ) ( ( (   ,   \033[1mKernel:\033[0m $KERNEL"
echo -e "    '-'-'-'   '-'-'-'    \033[1mPackages:\033[0m $PACKAGES"
echo -e "                         \033[1mBash:\033[0m $BASH_V"
echo " "
